- task: UiPathInstallPlatform-preview@2
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'HelloWorld'
    outputType: 'Process'
    orchestratorConnection: 'myuipath'
    outputPath: '$(Build.ArtifactStagingDirectory)\Packages\HelloWorld'